### PR TITLE
Update to velocity v3.1.1

### PR DESCRIPTION
**Pull request by dc138**
This pull request implements the changes needed to update from the old 1.x.x velocity API to the new one, allowing the plugin to run in up-to-date velocity versions.

### CODE REVIEW

**Comment by Tobi406** [comment]
Thank you very much for this PR. I honestly didn't think someone would take a look at this. Especially as I have been quite distant from the Minecraft community recently. Since I also would need to setup everything to test it again, I'll just trust you blindly and merge this.

**Comment by CtrlAiDel** [comment]
Thanks alot for this PR and this Merge.

I'm still amateur with plugins development and compilation. Could I expect a release from you Tobi, or could anyone build it for me please. That would be really appreciated. I can't wait to add some aliases to my Velocity proxy :) ! 

@Tobi406 @DarthChungo  Thanks again, have a good day!

**Comment by dc138** [comment]
You can download a precompiled JAR from my fork's releases tab. It should work out of the box with any modern velocity version.

**Comment by CtrlAiDel** [comment]
Thanks! I'll go try it out ! I really appreciate both of your work!

Have a good day

**Comment by CtrlAiDel** [comment]
Hello back, im sending this here and to via email also, sorry for the double post.

Thanks alot @DarthChungo for the aliasR update. I just set it up and I had a quick question.

These are my actual config:

aliases = [
    { name = "minigames", args = "(\\S*)", command = "server minigames", commandArgs = "$1" }
    { name = "mg", args = "(\\S*)", command = "server Minigames", commandArgs = "$1" }
    { name = "hardcore", args = "(\\S*)", command = "server Hardcore", commandArgs = "$1" }
    { name = "semihardcore", args = "(\\S*)", command = "server Hardcore", commandArgs = "$1" }
    { name = "shc", args = "(\\S*)", command = "server Hardcore", commandArgs = "$1" }
    { name = "hc", args = "(\\S*)", command = "server Hardcore", commandArgs = "$1" }
    { name = "h", args = "(\\S*)", command = "server Hardcore", commandArgs = "$1" }
    { name = "crea", args = "(\\S*)", command = "server Creative", commandArgs = "$1" }
    { name = "pvp", args = "(\\S*)", command = "server pvp", commandArgs = "$1" }
    { name = "sskyblock", args = "(\\S*)", command = "server Sskyblock", commandArgs = "$1" }
    { name = "ss", args = "(\\S*)", command = "server Sskyblock ", commandArgs = "$1" }
    { name = "tc", args = "(\\S*)", command = "server Tempcity", commandArgs = "$1" }
    { name = "tempcity", args = "(\\S*)", command = "server Tempcity", commandArgs = "$1" }
    { name = "main", args = "(\\S*)", command = "server Tempcity", commandArgs = "$1" }
    { name = "survival", args = "(\\S*)", command = "server Tempcity", commandArgs = "$1" }
]


But when I hit any of these aliases in game I receive this:

It's the equivalent of the command being either cut in two because of the spaces. I don't think the alias is capting the second word in the command.

Could you please help me with my config, or maybe find a solution to this in a future update? 

Thanks you. 

You can contact me on discord if needed: WeConnected 


image

**Comment by CtrlAiDel** [comment]
Ok here's my update:
I've modified the command to this:
{ name = "Minigames", args = "(Minigames)", command = "server", commandArgs = "$1" }

The command should now be working, but I am receiving this error: 
image

I will got report it to Velocity also.

I appreciate your support!

PS: Off course this is the good server name, I've tried with or without the capital letter...

**Comment by dc138** [comment]
The problem might be with the parenthesis surrouning the server name.
You might want to try with `{ name = "Minigames", args = "Minigames", command = "server", commandArgs = "$1" }`

**Comment by CtrlAiDel** [comment]
image

Sorry, it is not working. I am receiving this error. 

I tried to contact velocity discord yesterday, in the chat velocity help, but I haven't received no answer. I'm trying to reach them via the chat velocity-dev right now. I will send them this link so they can follow up the problem/conversation.

Thank you for the follow up have a great day

**Comment by CtrlAiDel** [comment]
Here is the follow up i've received. They ask me for the error in the console and here's what I've sent them and the feedback they gave me :) ! :

In the chat I've receive the message: An error occured while running this command.  

and in the console:

image

**Comment by Tobi406** [comment]
The issue could be that it tries to insert a RegEx match that doesn't exist, which is obviously a configuration error.

afaik, `args` is not required to be used, which also seems to be confirmed by the code. And if `args` is not used, neither is `commandArgs`. It's essentially `/[command] [commandArgs with args substitution]`

Maybe the following can potentially work: `{ name = "Minigames", args = "", command = "server minigames", commandArgs = "" }` ie. leave args empty, leave commandArgs empty and just put "server minigames" into command.

**Comment by CtrlAiDel** [comment]
I'll go and try that live away. Thanks for the follow up

**Comment by CtrlAiDel** [comment]
@Tobi406  
Thank you for the follow-up. It worked indeed. Thank you both for your work...can't wait to go create all my aliases :) ! 

Peace! 

I'll stop spamming this thread sorry!

**Pull request merged**
